const d3 = require('d3')

export const addDefs = (svg) =>{
  // FILTER for gooey!
  // Code taken from http://tympanus.net/codrops/2015/03/10/creative-gooey-effects/
  const defs = svg.append('defs')

  const gooey = defs.append('filter')
                    .attr('id','gooey')

  gooey.append('feGaussianBlur')
       .attr('in','SourceGraphic')
       .attr('stdDeviation','10')
       .attr('result','blur')
  gooey.append('feColorMatrix')
       .attr('in','blur')
       .attr('mode','matrix')
       .attr('values','1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7')
       .attr('result','gooey')
  gooey.append('feComposite')
       .attr('in','SourceGraphic')
       .attr('in2','goo')
       .attr('operator','atop')
  // END of GOOEY

  // Radial Gradients
  const lightRadialGradient = defs.append("radialGradient")
                                  .attr("id", "lightRadialGradient")

  lightRadialGradient.append("stop")
                     .attr("id", "stop_1")
                     .attr("offset", "0%")
                     .attr("stop-color", "#c9e9f6")

  lightRadialGradient.append("stop")
                     .attr("id", "stop_2")
                     .attr("offset", "80%")
                     .attr("stop-color", "#87ceeb")

  const siteRadialGradient = defs.append("radialGradient")
                                 .attr("id", "siteRadialGradient")

  siteRadialGradient.append("stop")
                    .attr("id", "stop_1")
                    .attr("offset", "0%")
                    .attr("stop-color", "#c9e9f6")

  siteRadialGradient.append("stop")
                    .attr("id", "stop_2")
                    .attr("offset", "80%")
                    .attr("stop-color", "#87ceeb")

  const radialGradient = defs.append("radialGradient")
                             .attr("id", "radialGradient")

  radialGradient.append("stop")
                .attr("offset", "0%")
                .attr("stop-color", "#87ceeb")

  radialGradient.append("stop")
                .attr("offset", "80%")
                .attr("stop-color", "#45b3e0")

  const nucleusRadialGradient = defs.append("radialGradient")
                             .attr("id", "nucleusRadialGradient")

  nucleusRadialGradient.append("stop")
                .attr("offset", "0%")
                .attr("stop-color", "#FFBF4C")

  nucleusRadialGradient.append("stop")
                .attr("offset", "80%")
                .attr("stop-color", "#FFBF4C")

  nucleusRadialGradient.append("stop")
                .attr("offset", "100%")
                .attr("stop-color", "#b24735")

  const mitochondriaRadialGradient = defs.append("radialGradient")
                             .attr("id", "mitochondriaRadialGradient")

  mitochondriaRadialGradient.append("stop")
                .attr("offset", "0%")
                .attr("stop-color", "#F5F5DC")

  mitochondriaRadialGradient.append("stop")
                .attr("offset", "70%")
                .attr("stop-color", "#F5F5DC")

  mitochondriaRadialGradient.append("stop")
                .attr("offset", "100%")
                .attr("stop-color", "#abab9a")

  // Linear Gradients

  const greenLinearGradient = defs.append("linearGradient")
                                  .attr("id", "greenLinearGradient")
                                  .attr("x1", "0%")
                                  .attr("y1", "0%")
                                  .attr("x2", "0%")
                                  .attr("y2", "100%")

  greenLinearGradient.append("stop")
                     .attr("offset", "20%")
                     .attr("stop-color", "#35AB16")
  greenLinearGradient.append("stop")
                     .attr("offset", "25%")
                     .attr("stop-color", "#41902C")
  greenLinearGradient.append("stop")
                     .attr("offset", "30%")
                     .attr("stop-color", "#35AB16")
  greenLinearGradient.append("stop")
                     .attr("offset", "35%")
                     .attr("stop-color", "#41902C")
  greenLinearGradient.append("stop")
                     .attr("offset", "40%")
                     .attr("stop-color", "#35AB16")
  greenLinearGradient.append("stop")
                     .attr("offset", "60%")
                     .attr("stop-color", "#35AB16")
  greenLinearGradient.append("stop")
                     .attr("offset", "65%")
                     .attr("stop-color", "#41902C")
  greenLinearGradient.append("stop")
                     .attr("offset", "70%")
                     .attr("stop-color", "#35AB16")
  greenLinearGradient.append("stop")
                     .attr("offset", "85%")
                     .attr("stop-color", "#35AB16")
  greenLinearGradient.append("stop")
                     .attr("offset", "90%")
                     .attr("stop-color", "#41902C")
  greenLinearGradient.append("stop")
                     .attr("offset", "95%")
                     .attr("stop-color", "#35AB16")

  const blueLinearGradient = defs.append("linearGradient")
                                  .attr("id", "blueLinearGradient")
                                  .attr("x1", "0%")
                                  .attr("y1", "0%")
                                  .attr("x2", "0%")
                                  .attr("y2", "100%")

  blueLinearGradient.append("stop")
                     .attr("offset", "10%")
                     .attr("stop-color", "#467ED8")
  blueLinearGradient.append("stop")
                     .attr("offset", "15%")
                     .attr("stop-color", "#3A1FB2")
  blueLinearGradient.append("stop")
                     .attr("offset", "20%")
                     .attr("stop-color", "#467ED8")
  blueLinearGradient.append("stop")
                     .attr("offset", "40%")
                     .attr("stop-color", "#467ED8")
  blueLinearGradient.append("stop")
                     .attr("offset", "45%")
                     .attr("stop-color", "#3A1FB2")
  blueLinearGradient.append("stop")
                     .attr("offset", "50%")
                     .attr("stop-color", "#467ED8")
  blueLinearGradient.append("stop")
                     .attr("offset", "70%")
                     .attr("stop-color", "#467ED8")
  blueLinearGradient.append("stop")
                     .attr("offset", "75%")
                     .attr("stop-color", "#3A1FB2")
  blueLinearGradient.append("stop")
                     .attr("offset", "80%")
                     .attr("stop-color", "#467ED8")
  blueLinearGradient.append("stop")
                     .attr("offset", "85%")
                     .attr("stop-color", "#3A1FB2")
  blueLinearGradient.append("stop")
                     .attr("offset", "90%")
                     .attr("stop-color", "#467ED8")


  const redLinearGradient = defs.append("linearGradient")
                                  .attr("id", "redLinearGradient")
                                  .attr("x1", "0%")
                                  .attr("y1", "0%")
                                  .attr("x2", "0%")
                                  .attr("y2", "100%")

  redLinearGradient.append("stop")
                     .attr("offset", "0%")
                     .attr("stop-color", "#E6827A")
  redLinearGradient.append("stop")
                     .attr("offset", "5%")
                     .attr("stop-color", "#E32516")
  redLinearGradient.append("stop")
                     .attr("offset", "10%")
                     .attr("stop-color", "#E6827A")
  redLinearGradient.append("stop")
                     .attr("offset", "15%")
                     .attr("stop-color", "#E32516")
  redLinearGradient.append("stop")
                     .attr("offset", "20%")
                     .attr("stop-color", "#E6827A")
  redLinearGradient.append("stop")
                     .attr("offset", "40%")
                     .attr("stop-color", "#E6827A")
  redLinearGradient.append("stop")
                     .attr("offset", "45%")
                     .attr("stop-color", "#E32516")
  redLinearGradient.append("stop")
                     .attr("offset", "50%")
                     .attr("stop-color", "#E6827A")
  redLinearGradient.append("stop")
                     .attr("offset", "70%")
                     .attr("stop-color", "#E6827A")
  redLinearGradient.append("stop")
                     .attr("offset", "75%")
                     .attr("stop-color", "#E32516")
  redLinearGradient.append("stop")
                     .attr("offset", "80%")
                     .attr("stop-color", "#E6827A")

  const greyLinearGradient = defs.append("linearGradient")
                                  .attr("id", "greyLinearGradient")
                                  .attr("x1", "0%")
                                  .attr("y1", "0%")
                                  .attr("x2", "0%")
                                  .attr("y2", "100%")

  greyLinearGradient.append("stop")
                     .attr("offset", "40%")
                     .attr("stop-color", "#C7C7C7")
  greyLinearGradient.append("stop")
                     .attr("offset", "45%")
                     .attr("stop-color", "#707070")
  greyLinearGradient.append("stop")
                     .attr("offset", "50%")
                     .attr("stop-color", "#C7C7C7")
  greyLinearGradient.append("stop")
                     .attr("offset", "55%")
                     .attr("stop-color", "#707070")
  greyLinearGradient.append("stop")
                     .attr("offset", "60%")
                     .attr("stop-color", "#C7C7C7")
  greyLinearGradient.append("stop")
                     .attr("offset", "80%")
                     .attr("stop-color", "#C7C7C7")
  greyLinearGradient.append("stop")
                     .attr("offset", "85%")
                     .attr("stop-color", "#707070")
  greyLinearGradient.append("stop")
                     .attr("offset", "90%")
                     .attr("stop-color", "#C7C7C7")
  greyLinearGradient.append("stop")
                     .attr("offset", "95%")
                     .attr("stop-color", "#707070")
  greyLinearGradient.append("stop")
                     .attr("offset", "100%")
                     .attr("stop-color", "#C7C7C7")

  const yellowLinearGradient = defs.append("linearGradient")
                                  .attr("id", "yellowLinearGradient")
                                  .attr("x1", "0%")
                                  .attr("y1", "0%")
                                  .attr("x2", "0%")
                                  .attr("y2", "100%")

  yellowLinearGradient.append("stop")
                     .attr("offset", "25%")
                     .attr("stop-color", "#E7FF29")
  yellowLinearGradient.append("stop")
                     .attr("offset", "30%")
                     .attr("stop-color", "#DBA10A")
  yellowLinearGradient.append("stop")
                     .attr("offset", "35%")
                     .attr("stop-color", "#E7FF29")
  yellowLinearGradient.append("stop")
                     .attr("offset", "40%")
                     .attr("stop-color", "#DBA10A")
  yellowLinearGradient.append("stop")
                     .attr("offset", "45%")
                     .attr("stop-color", "#E7FF29")
  yellowLinearGradient.append("stop")
                     .attr("offset", "50%")
                     .attr("stop-color", "#DBA10A")
  yellowLinearGradient.append("stop")
                     .attr("offset", "55%")
                     .attr("stop-color", "#E7FF29")
  yellowLinearGradient.append("stop")
                     .attr("offset", "60%")
                     .attr("stop-color", "#DBA10A")
  yellowLinearGradient.append("stop")
                     .attr("offset", "65%")
                     .attr("stop-color", "#E7FF29")
}
